export const estates = [
    { "nombre": "Aguascalientes" },
    { "nombre": "Baja California" },
    { "nombre": "Baja California Sur" },
    { "nombre": "Campeche" },
    { "nombre": "Coahuila" },
    { "nombre": "Colima" },
    { "nombre": "Chiapas" },
    { "nombre": "Chihuahua" },
    { "nombre": "Ciudad de Mexico" },
    { "nombre": "Durango" },
    { "nombre": "Guanajuato" },
    { "nombre": "Guerrero" },
    { "nombre": "Hidalgo" },
    { "nombre": "Jalisco" },
    { "nombre": "Estado de Mexico" },
    { "nombre": "Michoacan" },
    { "nombre": "Morelos" },
    { "nombre": "Nayarit" },
    { "nombre": "Nuevo Leon" },
    { "nombre": "Oaxaca" },
    { "nombre": "Puebla" },
    { "nombre": "Queretaro" },
    { "nombre": "Quintana Roo" },
    { "nombre": "San Luis Potosi" },
    { "nombre": "Sinaloa" },
    { "nombre": "Sonora" },
    { "nombre": "Tabasco" },
    { "nombre": "Tamaulipas" },
    { "nombre": "Tlaxcala" },
    { "nombre": "Veracruz" },
    { "nombre": "Yucatan" },
    { "nombre": "Zacatecas" } 
]