import { IJob } from "../interfaces/job-type";

export const mockJobs: IJob[] = [
  {
    _id: "job001",
    company_id: "comp001",
    recruiter_id: "rec001",
    title: "Operador de Montacargas",
    description: [
      "Manejo seguro de montacargas en almacén",
      "Carga y descarga de mercancía",
      "Control de inventario físico",
    ],
    required_experience: [
      "1 año mínimo en manejo de montacargas",
      "Certificación OSHA",
    ],
    skills: ["Manejo de inventarios", "Organización"],
    mode: "presencial",
    state: "Nuevo León",
    city: "Monterrey",
    salary: "12500",
    benefits: ["Vales de despensa", "Seguro médico"],
    currency: "MXN",
    company: "Almacenes del Norte",
    shift: "vespertino",
    partFullTime: "Tiempo completo",
    created_at: "2025/01/15",
    currentStatus: "Activa",
    numberOfApplicants: 8,
    isGoogleJob: false,
  },
  {
    title: "Ayudante de Cocina",
    _id: "job0525",
    company: "Restaurante Mariscos Mazatlán",
    description: [
      "Preparación de ingredientes",
      "Limpieza de área de trabajo",
      "Apoyo a chefs en línea de cocina",
    ],
    required_experience: ["Experiencia básica en cocina deseable"],
    mode: "presencial",
    state: "Sinaloa",
    city: "Mazatlán",
    salary: "7,800",
    currency: "MXN",
    shift: "mixto",
    partFullTime: "Medio tiempo",
    created_at: "2025/02/20",
    currentStatus: "Activa",
    isGoogleJob: true,
    numberOfApplicants: 12,
  },
  {
    _id: "job00345",
    company_id: "comp003",
    title: "Técnico en Mantenimiento",
    company: "Maquiladora Sonora",
    description: [
      "Mantenimiento preventivo a máquinas industriales",
      "Reparación de fallas eléctricas básicas",
      "Reporte de incidencias",
    ],
    required_education: [
      "Secundaria terminada",
      "Curso en electricidad básica",
    ],
    skills: ["Manejo de herramientas", "Diagnóstico de fallas"],
    mode: "presencial",
    state: "Sonora",
    city: "Hermosillo",
    salary: "15,200",
    benefits: ["Uniforme", "Transporte"],
    currency: "MXN",
    isGoogleJob: true,
    shift: "matutino",
    partFullTime: "Tiempo completo",
    created_at: "2025/03/01",
    currentStatus: "Activa",
    numberOfApplicants: 5,
  },
  {
    title: "Chofer Local",
    company: "Distribuidora de Bebidas",
    _id: "job0054151",
    description: [
      "Reparto de mercancía en ruta local",
      "Manejo de camioneta de 3.5 toneladas",
      "Control de inventario entregado",
    ],
    required_experience: ["Licencia tipo C vigente", "2 años de experiencia"],
    mode: "presencial",
    state: "Chihuahua",
    city: "Juárez",
    salary: "13,000",
    benefits: ["Comisiones por venta", "Gasolina pagada"],
    currency: "MXN",
    shift: "matutino",
    partFullTime: "Tiempo completo",
    created_at: "2025/01/30",
    currentStatus: "Activa",
    isGoogleJob: true,
    numberOfApplicants: 7,
  },
  {
    _id: "job00144155",
    recruiter_id: "rec005",
    title: "Empacador",
    company: "Empaques del Pacífico",
    description: [
      "Empaque de productos alimenticios",
      "Control de calidad visual",
      "Mantenimiento de área limpia",
    ],
    mode: "presencial",
    state: "Baja California",
    city: "Mexicali",
    salary: "8,500",
    currency: "MXN",
    shift: "nocturno",
    partFullTime: "Medio tiempo",
    created_at: "2025/03/04",
    isGoogleJob: true,
    currentStatus: "Activa",
    numberOfApplicants: 15,
  },
  {
    title: "Soldador",
    company_id: "comp01101",
    recruiter_id: "rec_01_01",
    _id: "job00541s1",
    company: "Talleres Industriales del Norte",
    description: [
      "Soldadura MIG y TIG",
      "Interpretación de planos",
      "Mantenimiento de equipo",
    ],
    required_experience: [
      "3 años experiencia comprobable",
      "Certificación en soldadura",
    ],
    skills: ["Manejo de mediciones", "Trabajo en altura"],
    mode: "presencial",
    state: "Coahuila",
    city: "Saltillo",
    salary: "18,000",
    benefits: ["Equipo de protección", "Bonos por productividad"],
    currency: "MXN",
    shift: "mixto",
    partFullTime: "Tiempo completo",
    created_at: "2025/02/10",
    currentStatus: "Activa",
    numberOfApplicants: 6,
  },
  {
    _id: "job005165147",
    company_id: "comp007",
    title: "Almacenista",
    company: "Distribuidora de Materiales",
    description: [
      "Control de inventario",
      "Entrada y salida de materiales",
      "Organización de almacén",
    ],
    required_experience: ["1 año en puestos similares"],
    skills: ["Manejo de inventarios", "Uso de scanner"],
    mode: "presencial",
    state: "Tamaulipas",
    city: "Reynosa",
    salary: "10,500",
    currency: "MXN",
    shift: "vespertino",
    partFullTime: "Tiempo completo",
    created_at: "2025/01/25",
    isGoogleJob: true,
    currentStatus: "Inactiva",
    numberOfApplicants: 0,
  },
  {
    title: "Limpieza Industrial",
    _id: "job00515141",
    company: "Servicios Integrales del Norte",
    description: [
      "Limpieza de áreas de producción",
      "Manejo de químicos de limpieza",
      "Seguimiento de protocolos",
    ],
    mode: "presencial",
    state: "Nuevo León",
    city: "Apodaca",
    salary: "9,000",
    benefits: ["Uniforme proporcionado", "Seguro de vida"],
    currency: "MXN",
    shift: "nocturno",
    partFullTime: "Tiempo completo",
    created_at: "2025/02/28",
    currentStatus: "Activa",
    numberOfApplicants: 3,
  },
  {
    _id: "job00516569",
    title: "Ayudante de Construcción",
    company: "Constructora del Norte",
    description: [
      "Apoyo en obras de construcción",
      "Carga y descarga de materiales",
      "Manejo básico de herramientas",
    ],
    mode: "presencial",
    state: "Sonora",
    city: "Nogales",
    salary: "9,500",
    currency: "MXN",
    shift: "matutino",
    partFullTime: "Tiempo completo",
    isGoogleJob: true,
    created_at: "2025/03/03",
    currentStatus: "Activa",
    numberOfApplicants: 9,
  },
  {
    title: "Operador de Producción",
    _id: "job065416501",
    company: "Plásticos del Noroeste",
    description: [
      "Operación de máquinas inyectoras",
      "Control de calidad básico",
      "Llenado de formatos de producción",
    ],
    required_experience: ["Experiencia en maquila deseable"],
    mode: "presencial",
    state: "Chihuahua",
    city: "Chihuahua",
    salary: "11,200",
    benefits: ["Bonos de puntualidad", "Capacitación"],
    currency: "MXN",
    shift: "mixto",
    partFullTime: "Tiempo completo",
    created_at: "2025/02/15",
    currentStatus: "Activa",
    numberOfApplicants: 11,
    isGoogleJob: true,
  },
  {
    _id: "job0114511",
    recruiter_id: "rec011",
    title: "Carnicero",
    company: "Carnicería La Norteña",
    description: [
      "Preparación de cortes de carne",
      "Atención a clientes",
      "Mantenimiento de vitrinas",
    ],
    skills: ["Conocimiento de cortes", "Manejo de cuchillos"],
    mode: "presencial",
    state: "Durango",
    city: "Durango",
    salary: "10,000",
    currency: "MXN",
    shift: "matutino",
    partFullTime: "Medio tiempo",
    created_at: "2025/01/18",
    isGoogleJob: true,
    currentStatus: "Activa",
    numberOfApplicants: 4,
  },
  {
    title: "Instalador de Aire Acondicionado",
    _id: "job151001",
    company: "Climatización del Norte",
    description: [
      "Instalación de equipos residenciales",
      "Mantenimiento preventivo",
      "Diagnóstico de fallas",
    ],
    required_experience: ["1 año de experiencia"],
    skills: ["Manejo de herramientas", "Conocimiento eléctrico básico"],
    mode: "hibrido",
    state: "Coahuila",
    city: "Torreón",
    salary: "14,000",
    benefits: ["Herramientas", "Comisiones por venta"],
    currency: "MXN",
    shift: "vespertino",
    partFullTime: "Tiempo completo",
    created_at: "2025/02/05",
    currentStatus: "Activa",
    numberOfApplicants: 6,
  },
  {
    _id: "job0115163",
    company_id: "comp013",
    title: "Vigilante",
    company: "Seguridad Privada del Norte",
    description: [
      "Vigilancia de instalaciones",
      "Control de acceso",
      "Rondines de seguridad",
    ],
    required_education: ["Secundaria terminada", "Curso de seguridad privada"],
    mode: "presencial",
    state: "Baja California Sur",
    city: "La Paz",
    salary: "11,500",
    benefits: ["Uniforme", "Seguro de gastos médicos mayores"],
    currency: "MXN",
    shift: "nocturno",
    partFullTime: "Tiempo completo",
    created_at: "2025/01/22",
    currentStatus: "Inactiva",
    isGoogleJob: true,
    numberOfApplicants: 2,
  },
  {
    title: "Costurera",
    _id: "job05416501",
    company: "Confecciones del Norte",
    description: [
      "Confección de prendas según patrones",
      "Manejo de máquinas industriales",
      "Control de calidad básico",
    ],
    required_experience: ["1 año en maquila textil"],
    skills: ["Manejo de máquina recta", "Conocimiento de telas"],
    mode: "presencial",
    state: "Aguascalientes",
    city: "Aguascalientes",
    salary: "9,800",
    currency: "MXN",
    shift: "matutino",
    partFullTime: "Medio tiempo",
    created_at: "2025/03/02",
    currentStatus: "Activa",
    numberOfApplicants: 10,
  },
  {
    _id: "job002115",
    recruiter_id: "rec015",
    title: "Jardinerero",
    company: "Servicios de Jardinería Norte",
    description: [
      "Mantenimiento de áreas verdes",
      "Podado de árboles y arbustos",
      "Manejo de equipo de jardinería",
    ],
    mode: "presencial",
    state: "Sinaloa",
    city: "Los Mochis",
    salary: "8,000",
    benefits: ["Herramientas proporcionadas"],
    currency: "MXN",
    shift: "matutino",
    partFullTime: "Medio tiempo",
    created_at: "2025/02/12",
    currentStatus: "Activa",
    numberOfApplicants: 3,
    isGoogleJob: false,
  },
];
